///////////////////////////////////////////////////////////
//  Kryterium.cs
//  Implementation of the Class Kryterium
//  Generated by Enterprise Architect
//  Created on:      22-sty-2023 21:07:32
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Kryterium { 

	private int ID;
	private String opis;

	public Kryterium(){

	}

	~Kryterium(){

	}

}//end Kryterium