 ///////////////////////////////////////////////////////////
//  Lingwistyk.cs
//  Implementation of the Class Lingwistyk
//  Generated by Enterprise Architect
//  Created on:      22-sty-2023 21:07:33
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Lingwistyk {

	public Lingwistyk(){

	}

	~Lingwistyk(){

	}

}//end Lingwistyk