///////////////////////////////////////////////////////////
//  Model.cs
//  Implementation of the Class Model
//  Generated by Enterprise Architect
//  Created on:      22-sty-2023 21:07:33
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Model {

	private int ID;
	private Kryterium kryterium;
 
	public Model(){

	}

	~Model(){

	}

}//end Model