///////////////////////////////////////////////////////////
//  Tekst.cs
//  Implementation of the Class Tekst
//  Generated by Enterprise Architect
//  Created on:      22-sty-2023 21:07:36
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Tekst {

	private int ID;
	private String tekst;

	public Tekst(){

	}

	~Tekst(){

	}

}//end Tekst