///////////////////////////////////////////////////////////
//  Uzytkownik.cs
//  Implementation of the Class Uzytkownik
//  Generated by Enterprise Architect
//  Created on:      22-sty-2023 21:07:37
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


public class Uzytkownik : Wynik {

	private String email;
	private int ID;
	private String imie;
	private String nazwisko;

	public Uzytkownik(){

	}

	~Uzytkownik(){

	}

	/// 
	/// <param name="tekst"></param>
	public Wynik porownajTekst(Tekst tekst){

		return null;
	}

}//end Uzytkownik