///////////////////////////////////////////////////////////
//  Wynik.cs
//  Implementation of the Class Wynik
//  Generated by Enterprise Architect
//  Created on:      22-sty-2023 21:07:39
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Wynik {

	private int ID;
	private String zapozyczenia;

	public Wynik(){

	}

	~Wynik(){

	}

}//end Wynik?